name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install tools
        run: |
          python -m pip install --upgrade pip pytest
          pip install coverage
          pip install openmeteo_requests
          pip install geopy
          pip install matplotlib
          pip install requests_cache
          pip install requests
          pip install pandas
          pip install retry_requests
          pip install datetime
          pip install sqlite3
          pip install csv
          pip install time

      - name: Test with unittest
        run: python3 -m unittest test_weather_data.py

      - name: Check code coverage
        run: |
          python3 -m coverage run -m unittest test.py
          python3 -m coverage report
          python3 -m coverage html

      - name: Archive code coverage HTML report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: htmlcov
